import Main from "../components/Main";
import Head from "next/head";
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Link from "next/link";
import { HiOutlineChevronDoubleUp } from "react-icons/hi";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Tobias Stokken | Full Stack Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      {/* Kontakt form funke ikke :( */}
      {/* <Contact /> */}
      <div className="flex justify-center py-12">
          <Link href="/#home">
            <div className="rounded-full shadow-lg shadow-gray-400 p-4 cursor-pointer hover:scale-105 ease-in duration-300">
              <HiOutlineChevronDoubleUp className="text-[#5651e5]" size={30} />
            </div>
          </Link>
        </div>
    </div>
  );
}
